apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-application
  namespace: argocd
spec: 
  project: default
  source:
    repoURL: https://github.com/psshri/kafka_cassandra_cd.git
    # repoURL: https://USERNAME:TOKEN@github.com/psshri/kafka_cassandra_cd.git
    targetRevision: HEAD
    path: kafka
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions: 
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true